extends:
  - eslint:recommended

rules:
  # Possible Errors
  for-direction: "error"
  getter-return: "error"
  no-console: "warn" # recommended
  no-prototype-builtins: "error"
  no-template-curly-in-string: "error"
  
  # Best Practices
  accessor-pairs: "error"
  array-callback-return: "error"
  consistent-return: "error"
  curly: ["error", "all"]
  default-case: "error"
  dot-location: ["error", "property"]
  eqeqeq: "error"
  guard-for-in: "error"
  no-alert: "warn"
  no-caller: "error"
  no-div-regex: "error"
  no-empty-function: "error"
  no-eq-null: "error"
  no-eval: "error"
  no-extend-native: "error"
  no-extra-bind: "error"
  no-extra-label: "error"
  no-floating-decimal: "error"
  no-implicit-coercion: "error"
  no-implied-eval: "error"
  no-invalid-this: "error"
  no-iterator: "error"
  no-labels: "error"
  no-lone-blocks: "error"
  no-loop-func: "error"
  no-multi-spaces: "error"
  no-multi-str: "error"
  no-new-func: "error"
  no-new-wrappers: "error"
  no-octal-escape: "error"
  no-param-reassign: "error"
  no-proto: "error"
  no-return-assign: "error"
  no-return-await: "error"
  no-script-url: "error"
  no-self-compare: "error"
  no-sequences: "error"
  no-throw-literal: "error"
  no-unmodified-loop-condition: "error"
  no-unused-expressions: "error"
  no-useless-call: "error"
  no-useless-concat: "error"
  no-useless-return: "error"
  no-void: "error"
  no-warning-comments: "warn"
  no-with: "error"
  prefer-promise-reject-errors: "error"
  radix: "error"
  require-await: "error"
  wrap-iife: ["error", "inside"]
  
  # Strict Mode
  strict: ["error", "global"]
  
  # Variables
  no-catch-shadow: "error"
  no-label-var: "error"
  no-shadow-restricted-names: "error"
  no-shadow: ["error", {"builtinGlobals": true}]
  no-undef-init: "error"
  no-unused-vars: ["error", {"args": "none"}] # recommended
  
  # Stylistic Issues
  array-bracket-newline: ["error", "consistent"]
  array-bracket-spacing: ["error", "never"]
  block-spacing: "error"
  brace-style: ["error", "1tbs", {"allowSingleLine": true}]
  camelcase: "error"
  comma-dangle: ["error", "always-multiline"]
  comma-spacing: "error"
  comma-style: "error"
  computed-property-spacing: "error"
  eol-last: "warn"
  func-call-spacing: "error"
  func-name-matching: "error"
  func-style: ["error", "declaration", {"allowArrowFunctions": true}]
  implicit-arrow-linebreak: "error"
  indent: ["warn", 2]
  jsx-quotes: "error"
  key-spacing: "error"
  keyword-spacing: "error"
  linebreak-style: ["error", "unix"]
  lines-between-class-members: ["warn", "never"]
  max-depth: ["warn", {"max": 5}]
  max-len: ["warn", {"code": 100, "ignoreStrings": true, "ignoreTemplateLiterals": true, "ignoreRegExpLiterals": true}]
  max-nested-callbacks: ["warn", {"max": 5}]
  max-params: ["warn", {"max": 5}]
  max-statements-per-line: ["warn", {"max": 2}]
  new-parens: "error"
  no-array-constructor: "error"
  no-mixed-operators: "error"
  no-multiple-empty-lines: ["warn", {"max": 1}]
  no-negated-condition: "error"
  no-nested-ternary: "error"
  no-new-object: "error"
  no-trailing-spaces: ["error", {"skipBlankLines": true}]
  no-underscore-dangle: ["error", {"allowAfterThis": true}]
  no-unneeded-ternary: "error"
  no-whitespace-before-property: "error"
  object-curly-spacing: "error"
  operator-linebreak: ["error", "after"]
  padded-blocks: ["warn", "never"]
  quote-props: ["error", "consistent"]
  quotes: ["error", "double", {"avoidEscape": true}]
  semi-spacing: "error"
  semi-style: "error"
  semi: "error"
  space-before-blocks: ["error", "always"]
  space-before-function-paren: ["error", "never"]
  space-in-parens: ["error", "never"]
  space-infix-ops: "error"
  space-unary-ops: "error"
  spaced-comment: "warn"
  switch-colon-spacing: "error"
  unicode-bom: "error"
  
  # ECMAScript 6
  arrow-parens: "error"
  arrow-spacing: "error"
  generator-star-spacing: "error"
  no-confusing-arrow: ["error", {"allowParens": true}]
  no-duplicate-imports: "error"
  no-useless-computed-key: "error"
  no-useless-constructor: "error"
  no-useless-rename: "error"
  no-var: "error"
  object-shorthand: ["error", "methods"]
  prefer-arrow-callback: "error"
  prefer-const: "error"
  prefer-numeric-literals: "error"
  prefer-rest-params: "error"
  prefer-spread: "error"
  rest-spread-spacing: "error"
  symbol-description: "error"
  template-curly-spacing: "error"
  yield-star-spacing: "error"
